version: '3.8'

services:
  # 젠킨스
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/homebrew/bin/docker-compose:/usr/local/bin/docker-compose
      - jenkins_home:/var/jenkins_home

    networks:
      - jenkins-network

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
